export const birthDateRegex = /^(\d{4}[-/](0[1-9]|1[0-2])[-/](0[1-9]|[12]\d|3[01])){0,10}$/;
export const timeRegex = /^(?:[01]\d|2[0-3]):[0-5]\d$/;
export const dateRegex = /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$/;
export const emailRegex = /^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/;
export const UserDefaultRol = 'Deportista';
export const DEFAUL_LIMIT = 30;
export const DEAFUL_PERMISSIONS = 'Generic';
export const COMBATSTATUS = ['winner', 'draw'];
export const allowedExtensions = ['.jpeg', '.jpg', '.png'];
export const expectedHeaders = ['NAME', 'LASTNAME', 'BIRTHDATE', 'CEDULA', 'EMAIL', 'WEIGHT', 'PHONE', 'ADDRESS'];
export const expectedHeadersTrainer = ['NAME', 'LASTNAME', 'BIRTHDATE', 'CEDULA', 'EMAIL', 'PHONE', 'ADDRESS'];
export const formatStringdDate = 'd-M-yyyy';